### ISSUE TITLE
Does this decode SMS

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [IanWraith/DMRDecode#11]
Hi Ian,

I am trying to find some code which can decode SMS so I can add this feature to the OpenGD77 firmware.

I found some posts saying that DRMDecode can decode SMS traffic,  But I had a quick look through this repo, but could not see anything obvious which does SMS decoding :-(

**Comment by IanWraith** [comment]
Hi Roger
From memory you can see the message in the raw ASCII dumps in the data PDUs containing them but it doesn't specifically parse and display them I'm afraid.
Ian

**Comment by rogerclarkmelbourne** [comment]
Hi Ian
No worries.

I've looked in the MMDVMHost code, but I don't think it parses and decodes SMS messages either.

I think possibly DSDPlus does it. But its closed source.

Anyway. Thanks for the quick respose

**Comment by rogerclarkmelbourne** [comment]
Ian

Sorry to ask a stupid question, but when you say you can see the ASCII of the message, is it in readable plain text?

For some reason I assumed that you meant it was ASCII but still encoded.

Can you confirm if the text could be extracted and displayed if I modified you code, but that the text would not need further decoding e.g through golay etc?

**Comment by IanWraith** [comment]
If the message is ASCII coded you will see the hex numbers that represent the ASCII letters in the data. The problem is DMR has what seems like 100s of options for text messages and they seem to be rarely used in the field.

**Comment by rogerclarkmelbourne** [comment]
OK.

Thanks.

SMS data seems to be proprietary and not documented by the manufacturers.

I the Brandmeister network, may be able to transcode between different manufacturers data, but that network is closed source and I can't even be sure they definitely do transcoding.

They may just pass the bytes as raw data without processing them :-(
