### ISSUE TITLE
Usage Info

### ISSUE THREAD

**Issue by alwinhb** [IanWraith/DMRDecode#14]
@IanWraith Thanks for the open source code, My question can we provide a sample audio file to the jar file? Also does it contains all three layers of DMR?

**Comment by IanWraith** [comment]
You could use VAC (Virtual Audio Cable) to pipe a recording of a DMR signal to the program.
It contains most of the each of the layers of the DMR protocol although I am sure I will have forgotten some lesser used aspects.

**Comment by alwinhb** [comment]
@IanWraith Thanks it worked. My next question is whether it contains code for Data Link and Control Layer of DMR?

**Comment by IanWraith** [comment]
Most of the control layer is there. As for Data Link it depends what you mean. Remember there are many user defined types of data and it is impossible to cover them all. Look at the source code to see what is decoded.

**Comment by alwinhb** [comment]
Thanks @IanWraith Any reference code for Tx(transmit) as well? Looks like this code is only for the receiver end

**Comment by IanWraith** [comment]
Which code do you mean ? If the colour code then both sides of the link use the same  one.

**Comment by alwinhb** [comment]
@IanWraith I mean does this source code contains complete code for DMR? Tier 1/2/3

**Comment by IanWraith** [comment]
Are you seeing any unknown frames when you use it to decode data ?

**Comment by alwinhb** [comment]
@IanWraith I am implementing DMR on my custom hardware from scratch and I am using your code as a reference for DMR protocol implementation. Thereby making sure it contains complete code for tier1/2/3 

Thank you in advance!

**Comment by IanWraith** [comment]
I'm not sure I would recommend that. DMRDecode decodes the parts of DMR which we saw in use and needed to decode. This is probably 90% of the standard but there are parts missing. I also spent much time adding support for manufacturer specific features of DMR that aren't in the standard. In addition development of DMRDecode stopped nearly 10 years ago so the standard has moved on since then.

**Comment by alwinhb** [comment]
@IanWraith Do you have any references for Handheld - Handheld voice samples for decoding it via DMRDecode

**Comment by IanWraith** [comment]
No sorry.
